---
# tasks file for cbkc-ansible-role-docker
- name: CFS Configure global proxy settings
  template:
    src: cfs_proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    owner: bin
    group: wheel
    mode: '0644'
  when:
      - cloudEnv == "CFS"

- name: TSD Configure global proxy settings
  template:
    src: tsd_proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    owner: bin
    group: wheel
    mode: '0644'
  when:
      - cloudEnv == "TSD"

- name: Add docker-ce repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Install reqs for Docker
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Install the latest version of docker-ce
  yum:
    name: docker-ce
    state: latest

- name: Configure docker default registry
  template:
    src: cfs_daemon.json.j2
    dest: /etc/docker/daemon.json
  when:
    - cloudEnv == "CFS"

- name: Configure docker default registry
  template:
    src: tsd_daemon.json.j2
    dest: /etc/docker/daemon.json
  when:
    - cloudEnv == "TSD"

- name: Trust internal certificates
  shell: "openssl s_client -servername {{ internalDockerRegistry }} -connect {{ internalDockerRegistry }} </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' >/tmp/{{ internalDockerRegistry }}.pem "

- name: Copy docker registry cert to docker trusted cert location
  copy:
    src: "/tmp/{{ internalDockerRegistry }}.pem"
    dest: /etc/docker/certs.d/"{{ internalDockerRegistry }}"/ca.crt

- name: Enable Docker service
  shell: systemctl enable docker.service
  become: true

- name: Restart Docker service
  shell: systemctl restart docker.service
  become: true